### ISSUE TITLE
randomgen does not build under numpy 1.18.1

### ISSUE THREAD

**Issue by garfi303** [bashtage/randomgen#251]
@bashtage , I am so sorry to bother you again.

I am unable to get randomgen to compile with numpy 1.18.1 and python 3.7.6 (Anaconda 2020.02 distribution).

My previous compile attempts gave a warning that randomgen was using a deprecated interface. Now I get these errors:
```
gcc -pthread -B /mnt/apps/anaconda3-2020.02/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I./randomgen -I/mnt/apps5/anaconda3-2020.02/lib/python3.7/site-packages/numpy/core/include -I/mnt/apps5/anaconda3-2020.02/include/python3.7m -c randomgen/bounded_integers.c -o build/temp.linux-x86_64-3.7/randomgen/bounded_integers.o -std=c99 -U__GNUC_GNU_INLINE__ -msse2
randomgen/bounded_integers.c: In function ‘__pyx_pf_5numpy_7ndarray___getbuffer__’:
randomgen/bounded_integers.c:21332:50: error: ‘NPY_C_CONTIGUOUS’ undeclared (first use in this function); did you mean ‘PyBUF_C_CONTIGUOUS’?
   __pyx_t_2 = ((!(PyArray_CHKFLAGS(__pyx_v_self, NPY_C_CONTIGUOUS) != 0)) != 0);
                                                  ^~~~~~~~~~~~~~~~
                                                  PyBUF_C_CONTIGUOUS
randomgen/bounded_integers.c:21332:50: note: each undeclared identifier is reported only once for each function it appears in
randomgen/bounded_integers.c:21388:50: error: ‘NPY_F_CONTIGUOUS’ undeclared (first use in this function); did you mean ‘NPY_C_CONTIGUOUS’?
   __pyx_t_2 = ((!(PyArray_CHKFLAGS(__pyx_v_self, NPY_F_CONTIGUOUS) != 0)) != 0);
                                                  ^~~~~~~~~~~~~~~~
                                                  NPY_C_CONTIGUOUS
randomgen/bounded_integers.c:21574:40: error: ‘PyArrayObject {aka struct tagPyArrayObject}’ has no member named ‘descr’
   __pyx_t_3 = ((PyObject *)__pyx_v_self->descr);
                                        ^~
In file included from /mnt/apps5/anaconda3-2020.02/include/python3.7m/pytime.h:6:0,
                 from /mnt/apps5/anaconda3-2020.02/include/python3.7m/Python.h:87,
                 from randomgen/bounded_integers.c:41:
randomgen/bounded_integers.c: In function ‘__pyx_f_5numpy_set_array_base’:
randomgen/bounded_integers.c:23218:27: error: ‘PyArrayObject {aka struct tagPyArrayObject}’ has no member named ‘base’; did you mean ‘ob_base’?
   Py_XDECREF(__pyx_v_arr->base);
                           ^
/mnt/apps5/anaconda3-2020.02/include/python3.7m/object.h:861:50: note: in definition of macro ‘Py_XDECREF’
         PyObject *_py_xdecref_tmp = (PyObject *)(op); \
                                                  ^~
randomgen/bounded_integers.c:23227:16: error: ‘PyArrayObject {aka struct tagPyArrayObject}’ has no member named ‘base’; did you mean ‘ob_base’?
   __pyx_v_arr->base = __pyx_v_baseptr;
                ^~~~
                ob_base
randomgen/bounded_integers.c: In function ‘__pyx_f_5numpy_get_array_base’:
randomgen/bounded_integers.c:23262:30: error: ‘PyArrayObject {aka struct tagPyArrayObject}’ has no member named ‘base’; did you mean ‘ob_base’?
   __pyx_t_1 = ((__pyx_v_arr->base == NULL) != 0);
                              ^~~~
                              ob_base
In file included from /mnt/apps5/anaconda3-2020.02/include/python3.7m/pytime.h:6:0,
                 from /mnt/apps5/anaconda3-2020.02/include/python3.7m/Python.h:87,
                 from randomgen/bounded_integers.c:41:
randomgen/bounded_integers.c:23294:44: error: ‘PyArrayObject {aka struct tagPyArrayObject}’ has no member named ‘base’; did you mean ‘ob_base’?
     __Pyx_INCREF(((PyObject *)__pyx_v_arr->base));
                                            ^
/mnt/apps5/anaconda3-2020.02/include/python3.7m/object.h:796:19: note: in definition of macro ‘Py_INCREF’
     ((PyObject *)(op))->ob_refcnt++)
                   ^~
randomgen/bounded_integers.c:23294:5: note: in expansion of macro ‘__Pyx_INCREF’
     __Pyx_INCREF(((PyObject *)__pyx_v_arr->base));
     ^~~~~~~~~~~~
randomgen/bounded_integers.c:23295:41: error: ‘PyArrayObject {aka struct tagPyArrayObject}’ has no member named ‘base’; did you mean ‘ob_base’?
     __pyx_r = ((PyObject *)__pyx_v_arr->base);
                                         ^~~~
                                         ob_base
error: command 'gcc' failed with exit status 1
$  python
Python 3.7.6 (default, Jan  8 2020, 19:59:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.18.1'
>>>
```

I am also unable to install your wheel:
```
$ pip install randomgen-1.19.2-cp36-cp36m-manylinux1_x86_64.whl
ERROR: randomgen-1.19.2-cp36-cp36m-manylinux1_x86_64.whl is not a supported wheel on this platform.
```

**Comment by bashtage** [comment]
Which cython are you using? It helps to use a recent one.

**Comment by bashtage** [comment]
You might need to upgrade your pip.

**Comment by garfi303** [comment]
Thanks for the rapid response!

```
$ pip --version
pip 20.0.2 from /mnt/apps/anaconda3-2020.02/lib/python3.7/site-packages/pip (python 3.7)
$ cython --version
Cython version 0.29.15
```
Doesn't look like I can update it:
```
$ conda update cython
Collecting package metadata (current_repodata.json): done
Solving environment: /

Updating cython is constricted by

anaconda -> requires cython==0.29.15=py37he6710b0_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`

done

# All requested packages already installed.
```

**Comment by bashtage** [comment]
Can you pip install pip - - upgrade?

**Comment by bashtage** [comment]
You seem to have the wrong wheel. You need the python 3.7 wheel by the look
of things. Perhaps download the wheel for 3.7 manually and then just do a
pip install /path/to/wheel/long-wheel-name.whl

**Comment by garfi303** [comment]
You are right! I did manually downloaded it, but I download cp36 and not cp37.

**Comment by garfi303** [comment]
Thanks for your help. I can use the wheel, even though I can't compile from sources.
```
foils-ITE-MASTER:root@ip-10-252-44-164$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import randomgen
>>> randomegen.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'randomegen' is not defined
>>> randomgen.__version__
'1.19.2'
>>>
```

**Comment by bashtage** [comment]
Just for google searches, it is also available [through conda-forge](https://anaconda.org/conda-forge/randomgen)

```
conda install -c conda-forge randomgen
```
